@startuml BibliotecaCodigo
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

class Libro {
  - String titulo
  - String autor
  - Date fechaPublicacion
  - boolean disponible

  + getTitulo() : String
  + getAutor() : String
  + getFechaPublicacion() : Date
  + verificarDisponibilidad() : boolean
}
@enduml
