@startuml BibliotecaContext
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(usuario, "Usuario", "Usuario que interactúa con el sistema")
System(sistemaGestao, "Sistema de Gestión de Biblioteca", "Sistema que gestiona el catálogo de libros y préstamos")
System_Ext(servicoPagamento, "Sistema de Pagos", "Sistema externo para el procesamiento de pagos")
System_Ext(servicoNotificacao, "Servicio de Notificaciones", "Servicio externo para enviar notificaciones")

Rel(usuario, sistemaGestao, "Utiliza")
Rel(sistemaGestao, servicoPagamento, "Procesa pagos")
Rel(sistemaGestao, servicoNotificacao, "Envía notificaciones")

@enduml
